create table users (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50)NOT NULL,
	dob DATE NOT NULL,
	email VARCHAR(250)NOT NULL UNIQUE,
	password VARCHAR(250) NOT NULL,
	image BYTEA,
	followers VARCHAR(250),
	following VARCHAR(250),
	likes VARCHAR(250)
);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (1, 'Cherish', 'Swatten', '2/23/2021', 'cswatten0@github.com', 'ViaX5QNFwb', 'http://dummyimage.com/125x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (2, 'Tyrus', 'Liepmann', '8/2/2021', 'tliepmann1@dyndns.org', 'NDt66Ez4VI', 'http://dummyimage.com/103x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (3, 'Hallsy', 'Dodge', '2/17/2021', 'hdodge2@wordpress.org', 'T0rwZfA', 'http://dummyimage.com/235x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (4, 'Chase', 'Forcade', '12/25/2021', 'cforcade3@weibo.com', 'VLveMgBUjQVX', 'http://dummyimage.com/116x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (5, 'Douglass', 'Wandrack', '11/13/2021', 'dwandrack4@yahoo.com', 'nGARnNh2GZK', 'http://dummyimage.com/219x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (6, 'Frankie', 'Gatiss', '3/18/2021', 'fgatiss5@sbwire.com', 'HbdqfUKYq', 'http://dummyimage.com/250x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (7, 'Marijn', 'Banck', '12/20/2021', 'mbanck6@ameblo.jp', 'S4xd4lMZ', 'http://dummyimage.com/180x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (8, 'Davide', 'Stanyan', '12/15/2021', 'dstanyan7@hostgator.com', 'yZhsIPOevFes', 'http://dummyimage.com/219x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (9, 'Matias', 'Dyter', '3/21/2021', 'mdyter8@wiley.com', '0SAEBz8', 'http://dummyimage.com/247x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (10, 'Anni', 'Crab', '4/27/2021', 'acrab9@reuters.com', 'RV1ECTFjvv9', 'http://dummyimage.com/204x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (11, 'Nathanil', 'Haugh', '6/9/2021', 'nhaugha@youtu.be', 'kuTMikKls7v', 'http://dummyimage.com/237x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (12, 'Diane-marie', 'Mailey', '8/16/2021', 'dmaileyb@newyorker.com', 'eQKY1gQGG8A', 'http://dummyimage.com/122x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (13, 'Arlene', 'Fishly', '6/7/2021', 'afishlyc@go.com', 'HSlwHvOAIR8', 'http://dummyimage.com/160x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (14, 'Zebulon', 'Osburn', '3/20/2021', 'zosburnd@japanpost.jp', 'ugrARZmdR8Cy', 'http://dummyimage.com/191x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (15, 'Boyd', 'Paute', '1/23/2021', 'bpautee@liveinternet.ru', 'bIH0akw1', 'http://dummyimage.com/108x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (16, 'Terencio', 'Geare', '9/28/2021', 'tgearef@com.com', 'FPjp88MY', 'http://dummyimage.com/111x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (17, 'Lindsey', 'Ludron', '10/4/2021', 'lludrong@nba.com', '6c2e0B', 'http://dummyimage.com/210x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (18, 'Donn', 'Tomasoni', '1/12/2022', 'dtomasonih@psu.edu', 'EYwukaazMh', 'http://dummyimage.com/190x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (19, 'Selia', 'Drewery', '10/22/2021', 'sdreweryi@unesco.org', 'HHNxzy', 'http://dummyimage.com/197x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (20, 'Carleton', 'Thornthwaite', '9/25/2021', 'cthornthwaitej@1688.com', 'KkhAb9', 'http://dummyimage.com/193x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (21, 'Stace', 'Reburn', '8/30/2021', 'sreburnk@howstuffworks.com', '2DcdZUO', 'http://dummyimage.com/178x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (22, 'Issie', 'Tippetts', '10/17/2021', 'itippettsl@360.cn', 'eLKX7t1PwcA', 'http://dummyimage.com/171x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (23, 'Vanya', 'Grimestone', '1/31/2021', 'vgrimestonem@google.nl', 'N36FPrBHlo', 'http://dummyimage.com/184x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (24, 'Pooh', 'Gomes', '9/21/2021', 'pgomesn@4shared.com', '9hpPjGvY09', 'http://dummyimage.com/150x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (25, 'Sharyl', 'Harnor', '7/18/2021', 'sharnoro@hibu.com', 'ROfobKf', 'http://dummyimage.com/197x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (26, 'Dianne', 'Worton', '4/9/2021', 'dwortonp@cargocollective.com', 'rkevb7', 'http://dummyimage.com/121x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (27, 'Win', 'Tante', '2/8/2021', 'wtanteq@cdc.gov', 'NOp5uhmS', 'http://dummyimage.com/172x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (28, 'Shelli', 'Tandey', '10/20/2021', 'standeyr@pbs.org', 'qb59SO4a6', 'http://dummyimage.com/164x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (29, 'Sonnnie', 'Birtchnell', '4/2/2021', 'sbirtchnells@bloglines.com', 'ZdVmWcQfJs', 'http://dummyimage.com/200x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (30, 'Justinian', 'Corhard', '10/2/2021', 'jcorhardt@google.pl', 'm2zATTQDa9', 'http://dummyimage.com/187x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (31, 'Augustin', 'Hefner', '5/30/2021', 'ahefneru@dell.com', 'SXKALsbeK', 'http://dummyimage.com/154x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (32, 'Eberto', 'Naris', '12/1/2021', 'enarisv@miibeian.gov.cn', 'YFBgvSc7jFzc', 'http://dummyimage.com/178x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (33, 'Benny', 'Marousek', '11/29/2021', 'bmarousekw@scribd.com', 'DtBozlBz4Tq', 'http://dummyimage.com/194x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (34, 'Caren', 'Chrippes', '10/12/2021', 'cchrippesx@amazon.co.jp', 'YPEvo3X', 'http://dummyimage.com/186x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (35, 'Rose', 'Solesbury', '2/9/2021', 'rsolesburyy@cpanel.net', 'ys36Tg', 'http://dummyimage.com/183x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (36, 'Sherie', 'Chesterfield', '11/22/2021', 'schesterfieldz@unicef.org', 'ak8m7FdXkYW', 'http://dummyimage.com/225x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (37, 'Agneta', 'Oldaker', '11/12/2021', 'aoldaker10@intel.com', '1eJ4scUd', 'http://dummyimage.com/183x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (38, 'Gunner', 'Castelin', '9/25/2021', 'gcastelin11@comcast.net', 'cyFlhE', 'http://dummyimage.com/222x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (39, 'Teddi', 'Edworthye', '1/9/2022', 'tedworthye12@craigslist.org', '9xzTZb6', 'http://dummyimage.com/131x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (40, 'Ermentrude', 'Helversen', '11/11/2021', 'ehelversen13@epa.gov', 'GM5uuTzCN', 'http://dummyimage.com/239x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (41, 'Gladi', 'Lande', '12/11/2021', 'glande14@cnet.com', 'DCOh7F', 'http://dummyimage.com/202x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (42, 'Eugenia', 'Malin', '5/11/2021', 'emalin15@engadget.com', 'LMPQvPAdF5uR', 'http://dummyimage.com/215x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (43, 'Langsdon', 'Norheny', '5/30/2021', 'lnorheny16@smh.com.au', 'ENh0qP45P', 'http://dummyimage.com/151x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (44, 'Ephrayim', 'Marley', '6/7/2021', 'emarley17@xing.com', 'dqTRFD', 'http://dummyimage.com/124x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (45, 'Skip', 'Skase', '9/5/2021', 'sskase18@apache.org', 'PlPj26oJ3', 'http://dummyimage.com/177x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (46, 'Netti', 'Flay', '12/23/2021', 'nflay19@newyorker.com', 'QCgzw7pa', 'http://dummyimage.com/114x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (47, 'Beau', 'Gudgeon', '3/15/2021', 'bgudgeon1a@bizjournals.com', 'dyvn2mDOGgw', 'http://dummyimage.com/244x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (48, 'Kalindi', 'Dudderidge', '12/11/2021', 'kdudderidge1b@odnoklassniki.ru', 'cqnj8qCSrhw', 'http://dummyimage.com/125x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (49, 'Ursola', 'Hucker', '9/23/2021', 'uhucker1c@quantcast.com', 'vlQoxvoQGv', 'http://dummyimage.com/189x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (50, 'Tobe', 'Marion', '5/4/2021', 'tmarion1d@slashdot.org', '4Au6gbf', 'http://dummyimage.com/124x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (51, 'Karry', 'Bellhanger', '5/7/2021', 'kbellhanger1e@flickr.com', 'ciTWBlcGOOpQ', 'http://dummyimage.com/129x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (52, 'Toby', 'Batrim', '4/11/2021', 'tbatrim1f@nytimes.com', 'TWQDRci', 'http://dummyimage.com/230x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (53, 'Yardley', 'Ace', '9/6/2021', 'yace1g@tripod.com', 'qe5yn8', 'http://dummyimage.com/208x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (54, 'Moore', 'Walding', '2/4/2021', 'mwalding1h@scribd.com', 'IEkDliM09', 'http://dummyimage.com/112x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (55, 'Linoel', 'Daviot', '10/26/2021', 'ldaviot1i@g.co', '3nMcqOP', 'http://dummyimage.com/144x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (56, 'Remy', 'Hulbert', '4/7/2021', 'rhulbert1j@newsvine.com', 'XhKBJsyUrJ', 'http://dummyimage.com/213x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (57, 'Shaw', 'Shakeshaft', '6/9/2021', 'sshakeshaft1k@bloomberg.com', 'UxJujUTFaa', 'http://dummyimage.com/195x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (58, 'Cleo', 'Pigny', '6/29/2021', 'cpigny1l@ox.ac.uk', 'HEdicusVb', 'http://dummyimage.com/142x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (59, 'Gaylord', 'Brumpton', '9/11/2021', 'gbrumpton1m@newyorker.com', '4NxEtkam', 'http://dummyimage.com/233x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (60, 'Faber', 'Tunmore', '9/25/2021', 'ftunmore1n@merriam-webster.com', '064qlhvqubV0', 'http://dummyimage.com/214x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (61, 'Anthe', 'Roberts', '10/5/2021', 'aroberts1o@unesco.org', 'JIfAbGQ', 'http://dummyimage.com/167x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (62, 'Mariellen', 'Clapton', '11/23/2021', 'mclapton1p@deliciousdays.com', 'JekbQrPhA', 'http://dummyimage.com/188x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (63, 'Tobie', 'Byllam', '7/3/2021', 'tbyllam1q@reuters.com', '9K53g2EivqaR', 'http://dummyimage.com/147x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (64, 'Terencio', 'Baudouin', '5/26/2021', 'tbaudouin1r@digg.com', 'ynB8fUF8H', 'http://dummyimage.com/230x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (65, 'Romain', 'Jacquet', '11/1/2021', 'rjacquet1s@xrea.com', 'zvhF7jRjB9', 'http://dummyimage.com/230x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (66, 'Tersina', 'O''Hone', '9/5/2021', 'tohone1t@skype.com', 'r53i68zZyQn', 'http://dummyimage.com/165x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (67, 'Estell', 'St Ange', '2/20/2021', 'estange1u@artisteer.com', 'y0rd4w', 'http://dummyimage.com/167x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (68, 'Kirbie', 'Bovey', '10/31/2021', 'kbovey1v@cbsnews.com', 'ELYe4Hwugy1', 'http://dummyimage.com/139x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (69, 'Lothaire', 'Coughan', '3/24/2021', 'lcoughan1w@cyberchimps.com', 'NUpU0V', 'http://dummyimage.com/170x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (70, 'Bebe', 'Kubec', '3/1/2021', 'bkubec1x@networkadvertising.org', 'kg1UNlkzVWh', 'http://dummyimage.com/226x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (71, 'Penelopa', 'Giraldo', '10/30/2021', 'pgiraldo1y@scientificamerican.com', '8QY20chQR', 'http://dummyimage.com/135x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (72, 'Tann', 'Olifard', '12/26/2021', 'tolifard1z@cdbaby.com', '7uc6e2', 'http://dummyimage.com/246x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (73, 'Blondy', 'Dahill', '6/29/2021', 'bdahill20@instagram.com', 'zStEcb1z', 'http://dummyimage.com/107x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (74, 'Kipp', 'Woolfitt', '2/11/2021', 'kwoolfitt21@buzzfeed.com', '52ynfjrt1', 'http://dummyimage.com/218x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (75, 'Deonne', 'Botterill', '2/25/2021', 'dbotterill22@php.net', 'F7shW5', 'http://dummyimage.com/114x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (76, 'Rod', 'Sibborn', '6/2/2021', 'rsibborn23@apache.org', 'J6iwfg', 'http://dummyimage.com/156x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (77, 'Mariellen', 'Duckworth', '3/19/2021', 'mduckworth24@symantec.com', '86yIemlK', 'http://dummyimage.com/234x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (78, 'Claudianus', 'Backshill', '6/7/2021', 'cbackshill25@alexa.com', 'FSJrDR0E', 'http://dummyimage.com/158x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (79, 'Sela', 'Dumbellow', '7/31/2021', 'sdumbellow26@blogspot.com', 'MUUN1Cr', 'http://dummyimage.com/107x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (80, 'Daile', 'Ezele', '3/18/2021', 'dezele27@example.com', 'bXxdZ8ZeW6', 'http://dummyimage.com/197x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (81, 'Michal', 'Langworthy', '12/8/2021', 'mlangworthy28@adobe.com', 'bYyqGHA4', 'http://dummyimage.com/203x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (82, 'Lynnea', 'Boddam', '6/27/2021', 'lboddam29@answers.com', '97SyU4s', 'http://dummyimage.com/106x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (83, 'Tomaso', 'Lafford', '4/20/2021', 'tlafford2a@theglobeandmail.com', 'IE1exeq2u', 'http://dummyimage.com/199x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (84, 'Jackie', 'Ong', '10/20/2021', 'jong2b@army.mil', 'BVfCUt', 'http://dummyimage.com/112x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (85, 'Oates', 'Holsall', '3/31/2021', 'oholsall2c@scientificamerican.com', 'TDpJTXAdJs', 'http://dummyimage.com/224x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (86, 'Dudley', 'Crump', '5/3/2021', 'dcrump2d@slashdot.org', 'Mo7xspAt', 'http://dummyimage.com/185x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (87, 'Renell', 'Gossop', '11/17/2021', 'rgossop2e@fema.gov', 'L6H5SAu', 'http://dummyimage.com/121x100.png/dddddd/000000', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (88, 'Ibbie', 'Trematick', '4/14/2021', 'itrematick2f@comcast.net', 'n138ECf', 'http://dummyimage.com/174x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (89, 'Janis', 'Lovick', '5/3/2021', 'jlovick2g@infoseek.co.jp', 'noE839VYH', 'http://dummyimage.com/144x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (90, 'Anderea', 'Magnay', '1/27/2021', 'amagnay2h@gmpg.org', 'c8EiKa', 'http://dummyimage.com/164x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (91, 'Fenelia', 'Morgan', '5/14/2021', 'fmorgan2i@wikimedia.org', '29BbvS2u', 'http://dummyimage.com/125x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (92, 'Jenelle', 'Ainsbury', '4/5/2021', 'jainsbury2j@epa.gov', 'cXruJCBp', 'http://dummyimage.com/245x100.png/ff4444/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (93, 'Dorella', 'Kasman', '11/4/2021', 'dkasman2k@businessinsider.com', 'V1zXyT6aR4', 'http://dummyimage.com/196x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (94, 'Lukas', 'Luberti', '3/17/2021', 'lluberti2l@walmart.com', 'gZzmBHN1BF', 'http://dummyimage.com/144x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (95, 'Afton', 'Wall', '4/2/2021', 'awall2m@acquirethisname.com', '2lXOp67r', 'http://dummyimage.com/103x100.png/5fa2dd/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (96, 'Gerhard', 'Currin', '8/12/2021', 'gcurrin2n@slate.com', '0GjHEayHa', 'http://dummyimage.com/106x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (97, 'Miof mela', 'Candish', '2/25/2021', 'mcandish2o@aol.com', 'VpmVwVEEXSL', 'http://dummyimage.com/217x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (98, 'Elwood', 'Benns', '12/26/2021', 'ebenns2p@moonfruit.com', 'eldkNEQo5Ke', 'http://dummyimage.com/246x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (99, 'Gabby', 'de Voiels', '12/27/2021', 'gdevoiels2q@slideshare.net', 'Nu8J9bzSBKV', 'http://dummyimage.com/250x100.png/cc0000/ffffff', null, null, null);
insert into users (id, first_name, last_name, dob, email, password, image, followers, following, like) values (100, 'Jermayne', 'Kinmond', '7/23/2021', 'jkinmond2r@dell.com', 'iivSB2QAjQnh', 'http://dummyimage.com/162x100.png/5fa2dd/ffffff', null, null, null);